name: Build Signed WebView Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Cordova CLI
        run: npm install -g cordova

      - name: Create Cordova project
        run: |
          rm -rf android-webapp
          mkdir android-webapp
          cd android-webapp
          cordova create . com.drasaclone.web WebApp
          cordova platform add android

      - name: Set WebView URL
        run: |
          cd android-webapp
          sed -i 's|<content src=.*|<content src="https://drasaclone.github.io/Web/" />|' config.xml

      - name: Build signed release APK
        run: |
          cd android-webapp
          cordova build android --release -- --gradleArg=-PcdvBuildMultipleApks=false

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: drasaclone-release-apk
          path: android-webapp/platforms/android/app/build/outputs/apk/release/app-release.apk
