name: Build DrasaClone Web Android App

on:
  workflow_dispatch:
    inputs:
      push_sender_id:
        description: 'FCM Sender ID'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Cordova CLI
        run: npm install -g cordova

      - name: Create Cordova project
        run: |
          rm -rf android-webapp
          mkdir -p android-webapp
          cd android-webapp
          cordova create . com.drasaclone.web DrasaCloneApp
          cordova platform add android

      - name: Build signed debug APK
        run: |
          cd android-webapp
          cordova build android --debug -- --gradleArg=-PcdvBuildMultipleApks=false

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: drasaclone-web-app-debug
          path: android-webapp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
