# .github/workflows/build-android.yml
name: Build and Sign Debug WebView APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Cordova CLI
        run: npm install -g cordova

      - name: Create Cordova project
        run: |
          rm -rf android-webapp
          mkdir android-webapp
          cd android-webapp
          cordova create . com.drasaclone.web WebApp
          cordova platform add android

      - name: Configure WebView URL
        run: |
          cd android-webapp
          sed -i 's|<content src=.*|<content src="https://drasaclone.github.io/Web/" />|' config.xml

      - name: Build signed debug APK
        run: |
          cd android-webapp
          cordova build android --debug -- --gradleArg=-PcdvBuildMultipleApks=false

      - name: Upload signed debug APK
        uses: actions/upload-artifact@v4
        with:
          name: drasaclone-signed-debug-apk
          path: android-webapp/platforms/android/app/build/outputs/apk/debug/app-debug.apk

# Lưu ý: Cordova tự động ký bản debug APK bằng debug keystore mặc định.
# Bạn chỉ cần tải về và cài app-debug.apk là đã có chữ ký, miễn bật nguồn ngoài và gỡ bản cũ.
