name: Build DrasaClone WebView App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js & Cordova
        run: |
          npm install -g cordova
          cordova -v

      - name: Build Android WebView
        run: |
          rm -rf android-webapp/platforms/android
          cd android-webapp
          cordova platform add android
          cordova build android --debug -- --gradleArg=-PcdvBuildMultipleApks=false

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: drasaclone-webview-debug-apk
          path: android-webapp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
