# .github/workflows/build-android.yml
name: Build WebView Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova project
        run: |
          rm -rf android-webapp
          mkdir android-webapp
          cd android-webapp
          cordova create . com.drasaclone.web WebApp
          cordova platform add android

      - name: Set WebView URL
        run: |
          cd android-webapp
          sed -i 's|<content src=.*|<content src="https://drasaclone.github.io/Web/" />|' config.xml

      - name: Build APK (debug)
        run: |
          cd android-webapp
          cordova build android --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: drasaclone-web-apk
          path: android-webapp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
