name: Build DrasaClone PWA → APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Initialize Bubblewrap project
        run: |
          rm -rf bubblewrap-project || true
          mkdir bubblewrap-project && cd bubblewrap-project
          bubblewrap init \
            --manifest="https://drasaclone.github.io/Web/manifest.webmanifest" \
            --packageId="com.drasaclone.web" \
            --appVersionName="1.0.0" \
            --appVersionCode="1" \
            --name="DrasaClone Web"

      - name: Build APK
        run: |
          cd bubblewrap-project
          bubblewrap build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: drasaclone-pwa-apk
          path: bubblewrap-project/build/*.apk
