# .github/workflows/build-android.yml
name: Build WebView Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Cordova CLI
        run: npm install -g cordova

      - name: Create Cordova project
        run: |
          rm -rf android-webapp
          mkdir android-webapp
          cd android-webapp
          cordova create . com.drasaclone.web WebApp
          cordova platform add android

      - name: Set WebView URL
        run: |
          cd android-webapp
          sed -i 's|<content src=.*|<content src="https://drasaclone.github.io/Web/" />|' config.xml

      - name: Build universal debug APK
        run: |
          cd android-webapp
          # Disable multiple APK splits to produce a universal APK
          cordova build android --debug -- --gradleArg=-PcdvBuildMultipleApks=false

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: drasaclone-web-universal-apk
          path: android-webapp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
