jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js & Cordova CLI
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install -g cordova@10

      - name: Create Cordova project
        run: cordova create build com.yourcompany.drasaclone DrasaClone

      - name: Generate config.xml
        run: |
          cat <<EOF > build/config.xml
          <!-- nội dung như trước -->
          EOF

      - name: Inspect repo structure
        run: ls -R .

      - name: Copy website into www/
        run: |
          rm -rf build/www
          mkdir -p build/www
          rsync -av --exclude='build' --exclude='.github' --exclude='.git' . build/www
          # nếu web ở Web/: rsync -av Web/ build/www/

      - name: Add platform & plugins
        run: |
          cd build
          npx cordova platform add android
          npx cordova plugin add cordova-plugin-inappbrowser
          npx cordova plugin add cordova-plugin-background-mode

      - name: Build Debug APK
        run: |
          cd build
          npx cordova build android --debug

      - uses: actions/upload-artifact@v4
        with:
          name: drasaclone-debug-apk
          path: build/platforms/android/app/build/outputs/apk/debug/app-debug.apk
