name: Build Cordova APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Cordova CLI
      run: npm install -g cordova@10

    - name: Prepare Cordova project
      working-directory: cordova
      run: |
        cordova platform add android
        cordova plugin add cordova-plugin-inappbrowser
        cordova plugin add cordova-plugin-background-mode

    - name: Build Android (Debug)
      working-directory: cordova
      run: cordova build android --debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: DrasaClone-debug
        path: cordova/platforms/android/app/build/outputs/apk/debug/app-debug.apk
